### ISSUE TITLE
Use standard python logger for logging.

### ISSUE THREAD

**Issue by F483** [Storj/pyp2p#17]
[This](https://github.com/Storj/pyp2p/blob/master/pyp2p/net.py#L218) is completely spamming all messages (not only the ones concerning itself).

You should use a [normal python logger](https://docs.python.org/2/library/logging.html) instead of [rolling your own](https://github.com/Storj/pyp2p/blob/master/pyp2p/net.py#L270).

This will allow others using your lib to have more control over logging.

**Comment by F483** [comment]
This hasn't been much of a problem until now, but I am enabling data transfer by default as it will be need for the test group c client. So all the pyp2p logs are now making the output completely unreadable.

**Comment by robertsdotpm** [comment]
Added logging and removed some excessive statements.
